version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: amazon
      POSTGRES_PASSWORD: amazon
      POSTGRES_DB: amazon
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
